routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\SmtpSettingController;
use App\Http\Controllers\LanguageSettingController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\ThemeSettingController;

Route::get('/', function () {
    return redirect()->route('login');
});

/* Account routes starts from here */
Route::group(['middleware' => 'auth'], function () {

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    // Cropper Model
    Route::get('cropper/{element}', [\App\Http\Controllers\ImageController::class, 'cropper'])->name('cropper');
    
    Route::get('/report', function () {
        return view('report.index');
    });
    
    Route::post('employees/apply-quick-action', [EmployeeController::class, 'applyQuickAction'])->name('employees.apply_quick_action');
    Route::get('employees/show-image', [EmployeeController::class, 'showImage'])->name('employees.show_image');
    Route::resource('employees', EmployeeController::class);

    // SMTP settings
    Route::get('smtp-settings/show-send-test-mail-modal', [SmtpSettingController::class, 'showTestEmailModal'])->name('smtp_settings.show_send_test_mail_modal');
    Route::get('smtp-settings/send-test-mail', [SmtpSettingController::class, 'sendTestEmail'])->name('smtp_settings.send_test_mail');
    Route::resource('smtp-settings', SmtpSettingController::class);

    // Language settings
    Route::post('language-settings/update-data/{id?}', [LanguageSettingController::class, 'updateData'])->name('language_settings.update_data');
    Route::resource('language-settings', LanguageSettingController::class);

    // Profile Settings
    Route::resource('profile', ProfileController::class);

    Route::post('theme-settings/{id}', [ThemeSettingController::class, 'updateNavbar'])->name('theme_settings.update_navbar');
    Route::resource('theme-settings', ThemeSettingController::class);

    // Settings
    Route::post('settings.update-general-settings/{id?}', [SettingController::class, 'updateGeneralSettings'])->name('settings.update_general_settings');
    Route::post('settings.delete-sessions', [SettingController::class, 'deleteSessions'])->name('settings.delete_sessions');
    Route::resource('settings', SettingController::class);

    Route::post('show-notifications', [NotificationController::class, 'showNotifications'])->name('show_notifications');
    Route::get('all-notifications', [NotificationController::class, 'all'])->name('all_notfications');
    Route::post('mark-read', [NotificationController::class, 'markRead'])->name('mark_single_notification_read');
    Route::post('mark_notification_read', [NotificationController::class, 'markAllRead'])->name('mark_notification_read');



});

app/Http/Controllers/LanguageSettingController.php
<?php

namespace App\Http\Controllers;

use App\Helper\Reply;
use App\Models\Language;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Barryvdh\TranslationManager\Models\Translation;
use App\Http\Requests\LanguageSettings\StoreRequest;
use App\Http\Requests\LanguageSettings\UpdateRequest;

class LanguageSettingController extends AccountBaseController
{

    public function __construct()
    {
        parent::__construct();
        $this->langPath = base_path() . '/resources/lang';
    }

    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create(Request $request)
    {
        return view('language-settings.create-language-settings-modal', $this->data);
    }

    /**
     * @param StoreRequest $request
     * @return array
     */
    public function store(StoreRequest $request)
    {
        // check and create lang folder
        $langExists = File::exists($this->langPath . '/' . strtolower($request->language_code));

        if (!$langExists) {
            File::makeDirectory($this->langPath . '/' . strtolower($request->language_code));
        }

        $setting = new Language();
        $setting->language_name = $request->language_name;
        $setting->language_code = $request->language_code;
        $setting->status = $request->status;
        $setting->save();
        session(['language_setting' => Language::where('status', 'active')->get()]);

        return Reply::success(__('messages.languageAdded'));
    }

    /**
     * @param Request $request
     * @param int $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function edit(Request $request, $id)
    {
        $this->language = Language::findOrFail($id);
        session(['language_setting' => Language::where('status', 'active')->get()]);
        return view('language-settings.edit-language-settings-modal', $this->data);
    }
    
    /**
     * update
     *
     * @param  Request $request
     * @param  mixed $id
     * @return array
     */
    // phpcs:ignore
    public function update(Request $request, $id)
    {
        $setting = Language::findOrFail($request->id);

        if ($request->has('status')) {
            $setting->status = $request->status;
        }

        $setting->save();
        session(['language_setting' => Language::where('status', 'active')->get()]);

        return Reply::success(__('messages.languageUpdated'));
    }

    /**
     * @param UpdateRequest $request
     * @param int $id
     * @return array
     */
    // phpcs:ignore
    public function updateData(UpdateRequest $request, $id)
    {
        $setting = Language::findOrFail($request->id);

        $oldLangExists = File::exists($this->langPath.'/'.strtolower($setting->language_code));

        if($oldLangExists){
            // check and create lang folder
            $langExists = File::exists($this->langPath . '/' . strtolower($request->language_code));

            if (!$langExists) {
                // update lang folder name
                File::move($this->langPath . '/' . strtolower($setting->language_code), $this->langPath . '/' . strtolower($request->language_code));

                Translation::where('locale', strtolower($setting->language_code))->get()->map(function ($translation) {
                    $translation->delete();
                });
            }
        }

        $setting->language_name = $request->language_name;
        $setting->language_code = strtolower($request->language_code);
        $setting->status = $request->status;
        $setting->save();

        session(['language_setting' => Language::where('status', 'active')->get()]);

        return Reply::success(__('messages.languageUpdated'));
    }

    /**
     * @param int $id
     * @return array
     */
    public function destroy($id)
    {
        $language = Language::findOrFail($id);
        $setting = global_setting();

        if ($language->language_code == $setting->locale) {
            $setting->locale = 'en';
            $setting->last_updated_by = $this->user->id;
            $setting->save();
            session()->forget('user');
        }

        $language->destroy($id);
        File::deleteDirectory($this->langPath.'/'.strtolower($language->language_code));
        session(['language_setting' => Language::where('status', 'active')->get()]);

        return Reply::success(__('messages.languageDeleted'));
    }

}

resources/views/language-settings/create-language-settings-modal.blade.php
<div class="modal-header">
    <h5 class="modal-title">@lang('app.add') @lang('app.language')</h5>
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
</div>
<div class="modal-body">
    <div class="portlet-body">
        <x-form id="createLanguage" method="POST" class="form-horizontal">
            <div class="row">

                <div class="col-lg-6">
                    <x-forms.text :fieldLabel="__('app.name')" fieldPlaceholder="Enter Language Name" fieldName="language_name" fieldId="language_name" fieldValue="" fieldRequired="true"/>
                </div>

                <div class="col-lg-6">
                    <x-forms.text :fieldLabel="__('app.language_code')" fieldPlaceholder="Enter Language Code" fieldName="language_code" fieldId="language_code" fieldValue="" fieldRequired="true"/>
                </div>

                <div class="col-lg-6">
                    <x-forms.select fieldId="status" :fieldLabel="__('app.status')" fieldName="status" search="true">
                        <option value="active">@lang('app.enabled')</option>
                        <option value="inactive">@lang('app.disabled')</option>
                    </x-forms.select>
                </div>

            </div>
        </x-form>
    </div>
</div>
<div class="modal-footer">
    <x-forms.button-cancel data-dismiss="modal" class="border-0 mr-3">@lang('app.cancel')</x-forms.button-cancel>
    <x-forms.button-primary id="save-language" icon="check">@lang('app.save')</x-forms.button-primary>
</div>

<script>

    $('#save-language').click(function () {
        $.easyAjax({
            container: '#createLanguage',
            type: "POST",
            disableButton: true,
            blockUI: true,
            buttonSelector: "#save-language",
            url: "{{route('language-settings.store')}}",
            data: $('#createLanguage').serialize(),
            success: function (response) {
                if (response.status == 'success') {
                    window.location.reload();
                }
            }
        })
    });

</script>

resources/views/language-settings/edit-language-settings-modal.blade.php
<div class="modal-header">
    <h5 class="modal-title">@lang('app.edit') @lang('app.language')</h5>
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
</div>
<div class="modal-body">
    <div class="portlet-body">
        <x-form id="editLanguage" method="POST" class="form-horizontal">
            <div class="row">
                <div class="col-lg-6">
                    <x-forms.text :fieldLabel="__('app.name')" fieldPlaceholder="Enter Language Name" fieldName="language_name" fieldId="language_name" :fieldValue="$language->language_name" fieldRequired="true"/>
                </div>

                <div class="col-lg-6">
                    <x-forms.text :fieldLabel="__('app.language_code')" fieldPlaceholder="Enter Language Code" fieldName="language_code" fieldId="language_code" :fieldValue="$language->language_code" fieldRequired="true"/>
                </div>

                <div class="col-lg-6">
                    <x-forms.select fieldId="status" :fieldLabel="__('app.status')" fieldName="status" search="true">
                        <option value="active" @if($language->status == 'active') selected @endif>@lang('app.enabled')</option>
                        <option value="inactive" @if($language->status == 'inactive') selected @endif>@lang('app.disabled')</option>
                    </x-forms.select>
                </div>
            </div>
        </x-form>
    </div>
</div>
<div class="modal-footer">
    <x-forms.button-cancel data-dismiss="modal" class="border-0 mr-3">@lang('app.cancel')</x-forms.button-cancel>
    <x-forms.button-primary id="save-language" icon="check">@lang('app.save')</x-forms.button-primary>
</div>

<script>

    $('#save-language').click(function () {
        $.easyAjax({
            container: '#editLanguage',
            type: "POST",
            disableButton: true,
            blockUI: true,
            buttonSelector: "#save-language",
            url: "{{route('language_settings.update_data', $language->id)}}",
            data: $('#editLanguage').serialize(),
            success: function (response) {
                if (response.status == 'success') {
                    window.location.reload();
                }
            }
        })
    });

</script>