routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\SmtpSettingController;
use App\Http\Controllers\LanguageSettingController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\ThemeSettingController;

Route::get('/', function () {
    return redirect()->route('login');
});

/* Account routes starts from here */
Route::group(['middleware' => 'auth'], function () {

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    // Cropper Model
    Route::get('cropper/{element}', [\App\Http\Controllers\ImageController::class, 'cropper'])->name('cropper');
    
    Route::get('/report', function () {
        return view('report.index');
    });
    
    Route::post('employees/apply-quick-action', [EmployeeController::class, 'applyQuickAction'])->name('employees.apply_quick_action');
    Route::get('employees/show-image', [EmployeeController::class, 'showImage'])->name('employees.show_image');
    Route::resource('employees', EmployeeController::class);

    // SMTP settings
    Route::get('smtp-settings/show-send-test-mail-modal', [SmtpSettingController::class, 'showTestEmailModal'])->name('smtp_settings.show_send_test_mail_modal');
    Route::get('smtp-settings/send-test-mail', [SmtpSettingController::class, 'sendTestEmail'])->name('smtp_settings.send_test_mail');
    Route::resource('smtp-settings', SmtpSettingController::class);

    // Language settings
    Route::post('language-settings/update-data/{id?}', [LanguageSettingController::class, 'updateData'])->name('language_settings.update_data');
    Route::resource('language-settings', LanguageSettingController::class);

    // Profile Settings
    Route::resource('profile', ProfileController::class);

    Route::post('theme-settings/{id}', [ThemeSettingController::class, 'updateNavbar'])->name('theme_settings.update_navbar');
    Route::resource('theme-settings', ThemeSettingController::class);

    // Settings
    Route::post('settings.update-general-settings/{id?}', [SettingController::class, 'updateGeneralSettings'])->name('settings.update_general_settings');
    Route::post('settings.delete-sessions', [SettingController::class, 'deleteSessions'])->name('settings.delete_sessions');
    Route::resource('settings', SettingController::class);

    Route::post('show-notifications', [NotificationController::class, 'showNotifications'])->name('show_notifications');
    Route::get('all-notifications', [NotificationController::class, 'all'])->name('all_notfications');
    Route::post('mark-read', [NotificationController::class, 'markRead'])->name('mark_single_notification_read');
    Route::post('mark_notification_read', [NotificationController::class, 'markAllRead'])->name('mark_notification_read');



});

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\EmployeesDataTable;
use App\Models\User;
use App\Http\Requests\Employee\StoreRequest;
use App\Http\Requests\Employee\UpdateRequest;
use App\Http\Controllers\AccountBaseController;
use App\Models\Country;
use App\Helper\Files;
use App\Helper\Reply;
use Illuminate\Support\Facades\Hash;
use Illuminate\Http\Request;

class EmployeeController extends AccountBaseController
{

    public function __construct()
    {
        parent::__construct();
        $this->pageTitle = __('modules.menu.employee');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    
    public function index(EmployeesDataTable $dataTable)
    {
        $this->users = User::all();
        
        return $dataTable->render('employees.index', $this->data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->pageTitle = __('app.add') . ' ' . __('app.employee');
        $this->countries = Country::all();
        $this->salutations = ['mr', 'mrs', 'miss', 'dr', 'sir', 'madam'];
        
        return view('employees.create', $this->data);
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $this->employee = User::withoutGlobalScope('active')->findOrFail($id);
        $html = view('employees.show', $this->data)->render();

        return Reply::dataOnly(['status' => 'success', 'html' => $html]);
    }

    public function store(StoreRequest $request)
    {
        $user = new User();

        if ($request->hasFile('image')) {
            Files::deleteFile($user->image, 'avatar');
            $user->image = Files::upload($request->image, 'avatar', 300);
        }

        $user->salutation = $request->salutation;
        $user->name = $request->name;
        $user->gender = $request->gender;
        $user->email = $request->email;
        $user->password = Hash::make($request->password);
        $user->date_of_birth = $request->date_of_birth;
        $user->joining_date = $request->joining_date;
        $user->mobile = $request->mobile;
        $user->address = $request->address;
        $user->save();

        return Reply::success(__('messages.employeeAdded'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->user = User::withoutGlobalScope('active')->findOrFail($id);

        $this->pageTitle = __('app.edit') . ' ' . __('app.employee');
        $this->countries = Country::all();
        $this->salutations = ['mr', 'mrs', 'miss', 'dr', 'sir', 'madam'];

        return view('employees.edit', $this->data);
    }

    /**
     * @param UpdateRequest $request
     * @param int $id
     * @return array
     */
    public function update(UpdateRequest $request, $id)
    {
        $user = User::withoutGlobalScope('active')->findOrFail($id);
        $user->salutation = $request->salutation;
        $user->name = $request->name;
        $user->gender = $request->gender;
        $user->email = $request->email;
        $user->date_of_birth = $request->date_of_birth;
        $user->joining_date = $request->joining_date;
        $user->mobile = $request->mobile;
        $user->address = $request->address;

        if ($request->password != '') {
            $user->password = Hash::make($request->password);
        }

        if (request()->has('status')) {
            $user->status = $request->status;
        }

        if ($request->image_delete == 'yes') {
            Files::deleteFile($user->image, 'avatar');
            $user->image = null;
        }

        if ($request->hasFile('image')) {
            Files::deleteFile($user->image, 'avatar');
            $user->image = Files::upload($request->image, 'avatar', 300);
        }

        $user->save();

        if (user()->id == $user->id) {
            session()->forget('user');
        }

        return Reply::successWithData(__('messages.updateSuccess'), ['redirectUrl' => route('employees.index')]);
    }

    /**
     * @param int $id
     * @return array
     */
    public function destroy($id)
    {
        $user = User::withoutGlobalScope('active')->findOrFail($id);

        if ($user->id == 1) {
            return Reply::error(__('messages.adminCannotDelete'));
        }

        User::withoutGlobalScope('active')->where('id', $id)->delete();

        return Reply::success(__('messages.employeeDeleted'));
    }

    public function showImage()
    {
        $this->imageUrl = request()->image_url;
        return view('show-image.index', $this->data);
    }

     /**
     * @param Request $request
     * @return array
     */
    public function applyQuickAction(Request $request)
    {
        switch ($request->action_type) {
        case 'delete':
            $this->deleteRecords($request);
                return Reply::success(__('messages.deleteSuccess'));
        case 'change-status':
            $this->changeStatus($request);
                return Reply::success(__('messages.statusUpdatedSuccessfully'));
        default:
            return Reply::error(__('messages.selectAction'));
        }
    }

    protected function deleteRecords($request)
    {
        User::withoutGlobalScope('active')->whereIn('id', explode(',', $request->row_ids))->delete();
    }

    protected function changeStatus($request)
    {
        User::withoutGlobalScope('active')->whereIn('id', explode(',', $request->row_ids))->update(['status' => $request->status]);
    }
    
}

app/View/Components/Employee.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class Employee extends Component
{

    public $user;
    public $disabledLink;

    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct($user, $disabledLink=null)
    {
        $this->user = $user;
        $this->disabledLink = $disabledLink;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|string
     */
    public function render()
    {
        return view('components.employee');
    }

}

resources/views/employees/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">

            <div class="col-lg-12 mb-4" id="table-actions">
                <x-forms.link-primary :link="route('employees.create')" class="mr-3 openRightModal" icon="plus">
                    @lang('app.add')
                    @lang('app.employee')
                </x-forms.link-primary>
            </div>

            <div class="col-lg-9">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">

                        <div class="col-12 px-0 d-lg-flex d-md-flex">
                            <h5 class="m-0 mt-1 w-30 text-capitalize">
                                Employees List 
                            </h5>

                            <x-datatable.actions>
                                <div class="select-status mr-3 pl-3 w-12rem">
                                    <select name="action_type" class="form-control select-picker" id="quick-action-type" disabled>
                                        <option value="">@lang('app.selectAction')</option>
                                        <option value="change-status">@lang('modules.tasks.changeStatus')</option>
                                        <option value="delete">@lang('app.delete')</option>
                                    </select>
                                </div>
                                <div class="select-status mr-3 d-none quick-action-field w-12rem" id="change-status-action">
                                    <select name="status" class="form-control select-picker">
                                        <option value="inactive">@lang('app.inactive')</option>
                                        <option value="active">@lang('app.active')</option>
                                    </select>
                                </div>
                            </x-datatable.actions>
                           
                        </div>

                    </div>
                    <div class="ibox-content">
                        {!! $dataTable->table(['class' => 'table table-hover border-0 w-100 table-sm']) !!}
                    </div>
                </div>
            </div>

            <div class="col-lg-3">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h4>Employee Details</h4>
                    </div>
                    <div class="ibox-content">
                        <div id="div_detail">
                            <x-cards.no-record icon="user" :message="__('messages.chooseEmployee')" />
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
@endsection

@section('scripts')


<!-- Datatables -->
<script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('vendor/datatables/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('vendor/datatables/responsive.bootstrap.min.js') }}"></script>
<script src="{{ asset('vendor/datatables/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('vendor/datatables/buttons.bootstrap4.min.js') }}"></script>
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>
{!! $dataTable->scripts() !!}

<script>
    $(document).ready(function() {
    
        const showTable = () => {
            window.LaravelDataTables["employees-table"].draw();
        }
    
        $('body').on('click', '.delete-table-row', function() {
            var id = $(this).data('user-id');
            Swal.fire({
                title: "@lang('messages.sweetAlertTitle')",
                text: "@lang('messages.recoverRecord')",
                icon: 'warning',
                showCancelButton: true,
                focusConfirm: false,
                confirmButtonText: "@lang('messages.confirmDelete')",
                cancelButtonText: "@lang('app.cancel')",
                customClass: {
                    confirmButton: 'btn btn-primary mr-3',
                    cancelButton: 'btn btn-secondary'
                },
                showClass: {
                    popup: 'swal2-noanimation',
                    backdrop: 'swal2-noanimation'
                },
                buttonsStyling: false
            }).then((result) => {
                if (result.isConfirmed) {
                    var url = "{{ route('employees.destroy', ':id') }}";
                    url = url.replace(':id', id);

                    var token = "{{ csrf_token() }}";

                    $.easyAjax({
                        type: 'POST',
                        url: url,
                        blockUI: true,
                        data: {
                            '_token': token,
                            '_method': 'DELETE'
                        },
                        success: function(response) {
                            if (response.status == "success") {
                                showTable();
                            }
                        }
                    });
                }
            });
        });
        
        $('body').on('click', '.view-detail', function() {
            var id = $(this).data('user-id');
          
            var url = "{{ route('employees.show', ':id') }}";
            url = url.replace(':id', id);

            var token = "{{ csrf_token() }}";

            $.easyAjax({
                type: 'GET',
                url: url,
                container: '#div_detail',
                blockUI: true,
                success: function(response) {
                    if (response.status == "success") {
                        $('#div_detail').html(response.html);
                    }
                }
            });

        });

        $('#quick-action-type').change(function() {
            const actionValue = $(this).val();
            if (actionValue != '') {
                $('#quick-action-apply').removeAttr('disabled');

                if (actionValue == 'change-status') {
                    $('.quick-action-field').addClass('d-none');
                    $('#change-status-action').removeClass('d-none');
                } else {
                    $('.quick-action-field').addClass('d-none');
                }
            } else {
                $('#quick-action-apply').attr('disabled', true);
                $('.quick-action-field').addClass('d-none');
            }
        });

        $('#quick-action-apply').click(function() {
            const actionValue = $('#quick-action-type').val();
            if (actionValue == 'delete') {
                Swal.fire({
                    title: "@lang('messages.sweetAlertTitle')",
                    text: "@lang('messages.recoverRecord')",
                    icon: 'warning',
                    showCancelButton: true,
                    focusConfirm: false,
                    confirmButtonText: "@lang('messages.confirmDelete')",
                    cancelButtonText: "@lang('app.cancel')",
                    customClass: {
                        confirmButton: 'btn btn-primary mr-3',
                        cancelButton: 'btn btn-secondary'
                    },
                    showClass: {
                        popup: 'swal2-noanimation',
                        backdrop: 'swal2-noanimation'
                    },
                    buttonsStyling: false
                }).then((result) => {
                    if (result.isConfirmed) {
                        applyQuickAction();
                    }
                });

            } else {
                applyQuickAction();
            }
        });

        const applyQuickAction = () => {
            var rowdIds = $("#employees-table input:checkbox:checked").map(function() {
                return $(this).val();
            }).get();

            var url = "{{ route('employees.apply_quick_action') }}?row_ids=" + rowdIds;

            $.easyAjax({
                url: url,
                container: '#quick-action-form',
                type: "POST",
                disableButton: true,
                buttonSelector: "#quick-action-apply",
                data: $('#quick-action-form').serialize(),
                blockUI: true,
                success: function(response) {
                    if (response.status == 'success') {
                        showTable();
                        resetActionButtons();
                        deSelectAll();
                    }
                }
            })
        };

    });
</script>

@endsection

resources/views/employees/show.blade.php
<x-cards.data-row :label="__('modules.employees.employeeId')" :value="$employee->id" />

<x-cards.data-row :label="__('modules.employees.fullName')" :value="ucwords($employee->name)" />

<x-cards.data-row :label="__('app.email')" :value="$employee->email" />

<x-cards.data-row :label="__('app.mobile')" :value="$employee->mobile ?? '--'" />

<x-cards.data-row :label="__('modules.employees.gender')" :value="$employee->gender ?? '--'" />

<x-cards.data-row :label="__('modules.employees.joiningDate')"
    :value="$employee->joining_date ? $employee->joining_date->format($global->date_format) : '--'" />

<x-cards.data-row :label="__('modules.employees.dateOfBirth')"
    :value="$employee->date_of_birth ? $employee->date_of_birth->format($global->date_format) : '--'" />

<x-cards.data-row :label="__('app.address')" :value="$employee->address ?? '--'" />

@if ($employee->image)
    <div class="col-12 px-0 pb-3 d-lg-flex d-md-flex">
        <p class="mb-0 text-lightest f-14 w-30 text-capitalize">{{ __('modules.employees.profileImage') }}</p>
        <p class="mb-0 text-dark-grey f-14 w-70 text-wrap">
            <a href="javascript:;" class="img-lightbox" data-image-url="{{ $employee->image_url }}">
                <img src="{{ $employee->image_url }}" width="80" height="80" class="img-thumbnail">
            </a>
        </p>
    </div>
@endif