routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\SmtpSettingController;
use App\Http\Controllers\LanguageSettingController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\ThemeSettingController;

Route::get('/', function () {
    return redirect()->route('login');
});

/* Account routes starts from here */
Route::group(['middleware' => 'auth'], function () {

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    // Cropper Model
    Route::get('cropper/{element}', [\App\Http\Controllers\ImageController::class, 'cropper'])->name('cropper');
    
    Route::get('/report', function () {
        return view('report.index');
    });
    
    Route::post('employees/apply-quick-action', [EmployeeController::class, 'applyQuickAction'])->name('employees.apply_quick_action');
    Route::get('employees/show-image', [EmployeeController::class, 'showImage'])->name('employees.show_image');
    Route::resource('employees', EmployeeController::class);

    // SMTP settings
    Route::get('smtp-settings/show-send-test-mail-modal', [SmtpSettingController::class, 'showTestEmailModal'])->name('smtp_settings.show_send_test_mail_modal');
    Route::get('smtp-settings/send-test-mail', [SmtpSettingController::class, 'sendTestEmail'])->name('smtp_settings.send_test_mail');
    Route::resource('smtp-settings', SmtpSettingController::class);

    // Language settings
    Route::post('language-settings/update-data/{id?}', [LanguageSettingController::class, 'updateData'])->name('language_settings.update_data');
    Route::resource('language-settings', LanguageSettingController::class);

    // Profile Settings
    Route::resource('profile', ProfileController::class);

    Route::post('theme-settings/{id}', [ThemeSettingController::class, 'updateNavbar'])->name('theme_settings.update_navbar');
    Route::resource('theme-settings', ThemeSettingController::class);

    // Settings
    Route::post('settings.update-general-settings/{id?}', [SettingController::class, 'updateGeneralSettings'])->name('settings.update_general_settings');
    Route::post('settings.delete-sessions', [SettingController::class, 'deleteSessions'])->name('settings.delete_sessions');
    Route::resource('settings', SettingController::class);

    Route::post('show-notifications', [NotificationController::class, 'showNotifications'])->name('show_notifications');
    Route::get('all-notifications', [NotificationController::class, 'all'])->name('all_notfications');
    Route::post('mark-read', [NotificationController::class, 'markRead'])->name('mark_single_notification_read');
    Route::post('mark_notification_read', [NotificationController::class, 'markAllRead'])->name('mark_notification_read');



});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>{{ $pageTitle }}</title>

      <link rel="icon" type="image/png" sizes="16x16" href="{{ $global->favicon_url }}">
      <meta name="msapplication-TileImage" content="{{ $global->favicon_url }}">

      {{-- Generated from webpack to minify several css files --}}
      <link href="{{ asset('css/dashboard-styles.css') }}" rel="stylesheet">

      {{-- For easyAjax and toastr --}}
      <link href="{{ asset('css/helper.css') }}" rel="stylesheet">

      {{-- Font Awesome --}}
      <link href="{{ asset('font-awesome/css/font-awesome.css') }}" rel="stylesheet">

      

      {{-- Custom CSS (Remove after all development) --}}
      <link href="{{ asset('css/bootstrap-4-utilities.css') }}" rel="stylesheet">

      {{-- select2 CSS --}}
      <link href="{{ asset('css/plugins/select2/select2.min.css') }}" rel="stylesheet">
      
      {{-- datepicker CSS --}}
      <link href="{{ asset('css/plugins/datapicker/datepicker3.css') }}" rel="stylesheet">
      
      {{-- dropify CSS --}}
      <link href="{{ asset('css/dropify.min.css') }}" rel="stylesheet">

      {{-- Custom CSS (Remove after all development) --}}
      <link href="{{ asset('css/custom.css') }}" rel="stylesheet">
   
      @stack('styles')
   </head>
   <body class="{{ ($user->mini_sidebar == 'true') ? 'mini-navbar' : '' }}">
      
      <div id="wrapper">
         @include('layouts.sidebar')
         @include('layouts.header')
         @include('layouts.configurations')

         

      </div>

      {{-- Jquery-2.1.1. --}}
      <script src="{{ asset('js/jquery-2.1.1.js') }}"></script>

      <script>
         const MODAL_DEFAULT = '#modal_default';
         const MODAL_LG = '#modal_lg';
         const MODAL_XL = '#modal_xl';
         const MODAL_XS = '#modal_xs';
         const MODAL_SM = '#modal_sm';
         const MODAL_TITLE = '#modal_title';
         const MODAL_SUB_TITLE = '#modal_sub_title';

         const GLOBAL_SETTINGS = @json(global_setting());
      
         const SELECT2_CONFIG = {
            placeholder: "Select Option",
            allowClear: true
         };

         const DROPIFY_MESSAGES = {
            default: '@lang("app.dragDrop")',
            replace: '@lang("app.dragDropReplace")',
            remove: '@lang("app.remove")',
            error: '@lang("app.largeFile")'
         };

         const DATEPICKER_CONFIGS = {
            format: "{{ global_setting()->moment_format }}",
            // startView: 1,
            clearBtn: false,
            // daysOfWeekDisabled: "0,1,2,3,4,5,6",
            daysOfWeekDisabled: "",
            daysOfWeekHighlighted: "",
            autoclose: true,
            todayHighlight: true,
            datesDisabled: [],
            toggleActive: true
         };

         $('body').on('click', '.img-lightbox', function() {
            var imageUrl = $(this).data('image-url');
            const url = "{{ route('employees.show_image').'?image_url=' }}"+encodeURIComponent(imageUrl);
            $(MODAL_DEFAULT + ' ' + MODAL_TITLE).html('...');
            $.ajaxModal(MODAL_DEFAULT, url);
         });

         //select row in datatable
         const dataTableRowCheck = (id) => {
            if ($(".select-table-row:checked").length > 0) {
               $("#quick-action-form").fadeIn();
               //if at-least one row is selected
               document.getElementById("select-all-table").indeterminate = true;
               $("#quick-actions")
                     .find("input, textarea, button, select")
                     .removeAttr("disabled");
               if ($("#quick-action-type").val() == "") {
                     $("#quick-action-apply").attr("disabled", true);
               }
               // $(".select-picker").selectpicker("refresh");
            } else {
               $("#quick-action-form").fadeOut();
               //if no row is selected
               document.getElementById("select-all-table").indeterminate = false;
               $("#select-all-table").attr("checked", false);
               resetActionButtons();
            }

            if ($("#datatable-row-" + id).is(":checked")) {
               $("#row-" + id).addClass("table-active");
            } else {
               $("#row-" + id).removeClass("table-active");
            }
         };

         //select all rows in datatable
         const selectAllTable = (source) => {
            checkboxes = document.getElementsByName("datatable_ids[]");
            for (var i = 0, n = checkboxes.length; i < n; i++) {
               // if disabled property is given to checkbox, it won't select particular checkbox.
               if (!$("#" + checkboxes[i].id).prop('disabled')){
                     checkboxes[i].checked = source.checked;
               }
               if ($("#" + checkboxes[i].id).is(":checked")) {
                     $("#" + checkboxes[i].id)
                        .closest("tr")
                        .addClass("table-active");
                     $("#quick-actions")
                        .find("input, textarea, button, select")
                        .removeAttr("disabled");
                     if ($("#quick-action-type").val() == "") {
                        $("#quick-action-apply").attr("disabled", true);
                     }
                     // $(".select-picker").selectpicker("refresh");
               } else {
                     $("#" + checkboxes[i].id)
                        .closest("tr")
                        .removeClass("table-active");
                     resetActionButtons();
               }
            }

            if ($(".select-table-row:checked").length > 0) {
               $("#quick-action-form").fadeIn();
            } else {
               $("#quick-action-form").fadeOut();
            }
         };

         //reset table action form elements
         const resetActionButtons = () => {
            $("#quick-action-form")[0].reset();
            $("#quick-actions")
               .find("input, textarea, button, select")
               .attr("disabled", "disabled");
            // $(".select-picker").selectpicker("refresh");
         };

         function deSelectAll() {
            $("#select-all-table").prop("checked", false);
         }

      </script>
      
      {{-- Generated from webpack to minify several script files --}}
      <script src="{{ asset('js/dashboard-scripts.js') }}"></script>

      {{-- Mentioned here because it not working with webpack --}}
      <script src="{{ asset('js/sweetalert2.min.js') }}"></script>

      {{-- For easyAjax and toastr --}}
      <script src="{{ asset('js/helper.js') }}"></script>
      
      {{-- select2 JS --}}
      <script src="{{ asset('js/plugins/select2/select2.full.min.js') }}"></script>
      
      {{-- datepicker JS --}}
      <script src="{{ asset('js/plugins/datapicker/bootstrap-datepicker.js') }}" charset="UTF-8"></script>
      
      {{-- dropify JS --}}
      <script src="{{ asset('js/dropify.min.js') }}"></script>

      <script>
         $(".select2").select2({ ...SELECT2_CONFIG});

         //initialise dropify
         var drEvent = $(".dropify").dropify({
            messages: DROPIFY_MESSAGES,
         });

         drEvent.on("dropify.afterClear", function (event, element) {
            var elementID = element.element.id;
            var elementName = element.element.name;
            if ($("#" + elementID + "_delete").length == 0) {
               $("#" + elementID).after(
                     '<input type="hidden" name="' +
                     elementName +
                     '_delete" id="' +
                     elementID +
                     '_delete" value="yes">'
               );
            }
         });

         $('.navbar-minimalize').on('click', function(e) {
            var url = "{{ route('theme_settings.update_navbar', [$user->id]) }}";
            $.easyAjax({
                url: url,
                type: "POST",
                data: {
                   "_token": "{{ csrf_token() }}",
                }
            });
        });

        $('.show-user-notifications').click(function() {
            var openStatus = $(this).attr('aria-expanded');

            if (typeof openStatus == "undefined" || openStatus == "false") {

                  var token = '{{ csrf_token() }}';
                  $.easyAjax({
                     type: 'POST',
                     url: "{{ route('show_notifications') }}",
                     container: "#notification-list",
                     blockUI: true,
                     data: {
                        '_token': token
                     },
                     success: function(data) {
                        if (data.status == 'success') {
                              $('#notification-list').html(data.html);
                        }
                     }
                  });
            }
         });

         $('body').on('click', '.mark-notification-read', function() {
            var token = '{{ csrf_token() }}';
            $.easyAjax({
                  type: 'POST',
                  url: "{{ route('mark_notification_read') }}",
                  blockUI: true,
                  data: {
                     '_token': token
                  },
                  success: function(data) {
                     if (data.status == 'success') {
                        $('.show-user-notifications span').html('0');
                        $('#notification-list').html(`<li>
                           <div class="text-center link-block">
                              <a href="javascript:;">
                                 <strong>@lang("messages.noNotification")</strong>
                              </a>
                           </div>
                        </li>`);
                     }
                  }
            });
         });

      </script>

      @yield('scripts')
   </body>
</html>

resources/views/layouts/configurations.blade.php
{{-- Logout Form --}}
<form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
    @csrf
</form>

{{-- Modal extra small --}}
<div class="modal inmodal fade" id="modal_xs" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-xs">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <h4 class="modal-title" id="modal_title">Modal title</h4>
                {{-- <small class="font-bold" id="modal_sub_title">Lorem Ipsum is simply dummy text of the printing and typesetting
                    industry.</small> --}}
            </div>
            <div class="modal-body">
                ...
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-white" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

{{-- Modal small --}}
<div class="modal inmodal fade" id="modal_sm" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <h4 class="modal-title" id="modal_title">Modal title</h4>
                {{-- <small class="font-bold" id="modal_sub_title">Lorem Ipsum is simply dummy text of the printing and typesetting
                    industry.</small> --}}
            </div>
            <div class="modal-body">
                ...
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-white" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>


{{-- Modal large --}}
<div class="modal inmodal fade" id="modal_lg" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <h4 class="modal-title" id="modal_title">Modal title</h4>
                {{-- <small class="font-bold" id="modal_sub_title">Lorem Ipsum is simply dummy text of the printing and typesetting
                    industry.</small> --}}
            </div>
            <div class="modal-body">
                ...
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-white" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>


{{-- Modal extra large --}}
<div class="modal inmodal fade" id="modal_xl" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <h4 class="modal-title" id="modal_title">Modal title</h4>
                {{-- <small class="font-bold" id="modal_sub_title">Lorem Ipsum is simply dummy text of the printing and typesetting
                    industry.</small> --}}
            </div>
            <div class="modal-body">
                ...
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-white" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>


{{-- Modal default --}}
<div class="modal inmodal" id="modal_default" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content animated bounceInRight">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <i class="fa fa-laptop modal-icon"></i>
                <h4 class="modal-title" id="modal_title">Modal title</h4>
                {{-- <small class="font-bold" id="modal_sub_title">Lorem Ipsum is simply dummy text of the printing and typesetting
                    industry.</small> --}}
            </div>
            <div class="modal-body">
               ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-white" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

resources/views/layouts/header.blade.php
<div id="page-wrapper" class="gray-bg">
   <div class="row border-bottom">
      <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
         <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="javascript:;"><i class="fa fa-bars"></i> </a>
            <form role="search" class="navbar-form-custom" action="">
               <div class="form-group">
                  <input type="text" placeholder="Search for something..." class="form-control" name="top-search"
                     id="top-search">
               </div>
            </form>
         </div>
         <ul class="nav navbar-top-links navbar-right">
            <li>
               <span class="m-r-sm text-muted welcome-message">Welcome to Sample</span>
            </li>
            <li class="dropdown">
               <a class="dropdown-toggle count-info show-user-notifications" data-toggle="dropdown" href="#">
                  <i class="fa fa-bell"></i> <span class="label label-warning">{{$user->unreadNotifications->count()}}</span>
               </a>
               <ul class="dropdown-menu dropdown-messages" id="notification-list">
               </ul>
            </li>
            <li>
               <a href="{{ route('logout') }}" onclick="event.preventDefault();
                     document.getElementById('logout-form').submit();">
                  <i class="fa fa-sign-out"></i> Log out
               </a>
            </li>
         </ul>
      </nav>
   </div>
   
   <x-app-title class="d-none d-lg-flex" :pageTitle="__($pageTitle)"></x-app-title>

   @yield('content')
   
   <div class="footer">
      <div class="pull-right">
         Designed & Developed By<strong onclick="window.open('http://www.amitchandrakar.com/', '_blank')"> Amit
            Chandrakar</strong>.
      </div>
      <div>
         <strong>Copyright</strong> &copy; 2020-2025
      </div>
   </div>
</div>

resources/views/layouts/sidebar.blade.php
<nav class="navbar-default navbar-static-side" role="navigation">
   <div class="sidebar-collapse">
      <ul class="nav metismenu" id="side-menu">
         <li class="nav-header">
            <div class="dropdown profile-element text-center">
               <span>
                  @php
                  $userImage = $user->hasGravatar($user->email) ? str_replace('?s=200&d=mp', '', $user->image_url) :
                  asset('images/avatar.png');
                  @endphp
                  <img alt="image" class="img-circle profile-image-sidebar" src="{{ ($user->image ? $user->image_url : $userImage) }}" />
               </span>
               <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                  <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold">{{ $user->name }} </strong>
                     </span> <span class="text-muted text-xs block">Developer <b class="caret"></b></span> </span>
               </a>
               <ul class="dropdown-menu animated fadeInRight m-t-xs">
                  <li><a href="{{ route('settings.index') }}">Profile</a></li>
                  <li>
                     <a href="{{ route('logout') }}" onclick="event.preventDefault();
                     document.getElementById('logout-form').submit();">Logout</a>
                  </li>
               </ul>
            </div>
            <div class="logo-element">
               <a href="{{ route('dashboard') }}">
                  <img class="rounded mt-0" height="40px" width="40px" src="{{ $global->logo_url }}" alt="Logo">
               </a>
            </div>
         </li>
         <li class="{{ request()->is('dashboard') ? 'active' : '' }}">
            <a href="/dashboard"><i class="fa fa-home"></i> <span class="nav-label">{{ __('modules.menu.dashboard')
                  }}</span></a>
         </li>
         <li class="{{ in_array($currentRouteName, ['employees.index', 'employees.edit', 'employees.create']) ? 'active' : '' }}">
            <a href="{{ route('employees.index') }}"><i class="fa fa-users"></i> <span class="nav-label">{{ __('modules.menu.employee') }}
            </span></a>
         </li>
         <li class="{{ in_array($currentRouteName, ['settings.index']) ? 'active' : '' }}">
            <a href="{{ route('settings.index') }}"><i class="fa fa-cog"></i> <span class="nav-label">{{ __('modules.menu.setting') }}</span></a>
         </li>
      </ul>
   </div>
</nav>